Traceback (most recent call last):
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import tensorflow as tf

print("GPU disponible:", tf.config.list_physical_devices('GPU'))

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mtensorflow[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mtf[39;00m
[0;32m      3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mGPU disponible:[39m[38;5;124m"[39m, tf[38;5;241m.[39mconfig[38;5;241m.[39mlist_physical_devices([38;5;124m'[39m[38;5;124mGPU[39m[38;5;124m'[39m))

[1;31mModuleNotFoundError[0m: No module named 'tensorflow'

